services:
  herakles-exporter:
    image: herakles-node-exporter:latest
    build: .
    container_name: herakles-exporter
    ports:
      - "9215:9215"
    volumes:
      - /proc:/host/proc:ro
    restart: unless-stopped