name: Test Build

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches-ignore:
      - lint-autofix/**
  push:
    branches-ignore:
      - lint-autofix/**

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build-and-test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Test eBPF Binary
        uses: ./.github/actions/build-and-test
